package mycourse.onkshare.model;

public class FileMap extends FileMapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_map.path
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_map.hold
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    private Long hold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_map.path
     *
     * @return the value of tb_file_map.path
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_map.path
     *
     * @param path the value for tb_file_map.path
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_map.hold
     *
     * @return the value of tb_file_map.hold
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public Long getHold() {
        return hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_map.hold
     *
     * @param hold the value for tb_file_map.hold
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public void setHold(Long hold) {
        this.hold = hold;
    }
}