package mycourse.onkshare.model;

public class FileMapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_map.storage_id
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    private String storageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_map.storage_method
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    private String storageMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_map.storage_id
     *
     * @return the value of tb_file_map.storage_id
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public String getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_map.storage_id
     *
     * @param storageId the value for tb_file_map.storage_id
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public void setStorageId(String storageId) {
        this.storageId = storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_map.storage_method
     *
     * @return the value of tb_file_map.storage_method
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_map.storage_method
     *
     * @param storageMethod the value for tb_file_map.storage_method
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    public void setStorageMethod(String storageMethod) {
        this.storageMethod = storageMethod;
    }
}