package mycourse.onkshare.model;

import java.util.Date;

public class FileDesc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_desc.file_id
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_desc.created
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_desc.updated
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_desc.file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    private String fileDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_desc.file_id
     *
     * @return the value of tb_file_desc.file_id
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_desc.file_id
     *
     * @param fileId the value for tb_file_desc.file_id
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_desc.created
     *
     * @return the value of tb_file_desc.created
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_desc.created
     *
     * @param created the value for tb_file_desc.created
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_desc.updated
     *
     * @return the value of tb_file_desc.updated
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_desc.updated
     *
     * @param updated the value for tb_file_desc.updated
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_desc.file_desc
     *
     * @return the value of tb_file_desc.file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public String getFileDesc() {
        return fileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_desc.file_desc
     *
     * @param fileDesc the value for tb_file_desc.file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    public void setFileDesc(String fileDesc) {
        this.fileDesc = fileDesc;
    }
}