package mycourse.onkshare.model;

import java.util.Date;

public class FileComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.file_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.parent_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.text
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private String text;

    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.user_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.floor
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.level
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.status
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.disagree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long disagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.agree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Long agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file_comment.created
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.id
     *
     * @return the value of tb_file_comment.id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.id
     *
     * @param id the value for tb_file_comment.id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.file_id
     *
     * @return the value of tb_file_comment.file_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.file_id
     *
     * @param fileId the value for tb_file_comment.file_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.parent_id
     *
     * @return the value of tb_file_comment.parent_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.parent_id
     *
     * @param parentId the value for tb_file_comment.parent_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.text
     *
     * @return the value of tb_file_comment.text
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.text
     *
     * @param text the value for tb_file_comment.text
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setText(String text) {
        this.text = text;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.user_id
     *
     * @return the value of tb_file_comment.user_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.user_id
     *
     * @param userId the value for tb_file_comment.user_id
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.floor
     *
     * @return the value of tb_file_comment.floor
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.floor
     *
     * @param floor the value for tb_file_comment.floor
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setFloor(Long floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.level
     *
     * @return the value of tb_file_comment.level
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.level
     *
     * @param level the value for tb_file_comment.level
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setLevel(Long level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.status
     *
     * @return the value of tb_file_comment.status
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.status
     *
     * @param status the value for tb_file_comment.status
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.disagree
     *
     * @return the value of tb_file_comment.disagree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getDisagree() {
        return disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.disagree
     *
     * @param disagree the value for tb_file_comment.disagree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setDisagree(Long disagree) {
        this.disagree = disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.agree
     *
     * @return the value of tb_file_comment.agree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Long getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.agree
     *
     * @param agree the value for tb_file_comment.agree
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setAgree(Long agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file_comment.created
     *
     * @return the value of tb_file_comment.created
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file_comment.created
     *
     * @param created the value for tb_file_comment.created
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}