package mycourse.onkshare.model;

import java.util.Date;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notification.id
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notification.content
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notification.created
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notification.updated
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notification.id
     *
     * @return the value of tb_notification.id
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notification.id
     *
     * @param id the value for tb_notification.id
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notification.content
     *
     * @return the value of tb_notification.content
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notification.content
     *
     * @param content the value for tb_notification.content
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notification.created
     *
     * @return the value of tb_notification.created
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notification.created
     *
     * @param created the value for tb_notification.created
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notification.updated
     *
     * @return the value of tb_notification.updated
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notification.updated
     *
     * @param updated the value for tb_notification.updated
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}