package mycourse.onkshare.mapper;

import java.util.List;
import mycourse.onkshare.model.FileMap;
import mycourse.onkshare.model.FileMapExample;
import mycourse.onkshare.model.FileMapKey;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface FileMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    long countByExample(FileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int deleteByExample(FileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int deleteByPrimaryKey(FileMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int insert(FileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int insertSelective(FileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    List<FileMap> selectByExample(FileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    FileMap selectByPrimaryKey(FileMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileMap record, @Param("example") FileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int updateByExample(@Param("record") FileMap record, @Param("example") FileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int updateByPrimaryKeySelective(FileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_map
     *
     * @mbg.generated Thu Mar 02 10:23:30 CST 2017
     */
    int updateByPrimaryKey(FileMap record);
}