package mycourse.onkshare.mapper;

import java.util.List;
import java.util.Map;

import mycourse.onkshare.model.FileComment;
import mycourse.onkshare.model.FileCommentExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface FileCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    long countByExample(FileCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int deleteByExample(FileCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int insert(FileComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int insertSelective(FileComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    List<FileComment> selectByExample(FileCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    FileComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileComment record, @Param("example") FileCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int updateByExample(@Param("record") FileComment record, @Param("example") FileCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int updateByPrimaryKeySelective(FileComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_comment
     *
     * @mbg.generated Tue Mar 28 18:30:15 CST 2017
     */
    int updateByPrimaryKey(FileComment record);

    List<FileComment> selectFileComment(Map conditions);

    Long selectFileCommentFloorMax(Long fileId);
}