package mycourse.onkshare.mapper;

import java.util.List;
import java.util.Map;

import mycourse.onkshare.model.File;
import mycourse.onkshare.model.FileExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    long countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    Long insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    List<File> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    File selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int updateByExample(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated Wed Mar 01 14:43:47 CST 2017
     */
    int updateByPrimaryKey(File record);

    List<File> selectFileByUserIdAndParentId(Map conditions);

    File selectFileByUserIdAndParentIdAndName(Map conditions);

    File selectFileByUserIdAndUrl(Map conditions);

    int updateFileStatusToOneByIds(Long[] ids);

    int updateFileStatusToZeroByIds(Long[] unIds);

    int updateFileStatusToTwoByIds(Long[] indIds);

    int selectFileMaxLevelByUserIdAndStatus(Map conditions);

    List<File> selectLevelFileExamplesByUserIdAndLevelAndStatus(Map conditions);

    List<File> selectUsersTopFolderByParentIdForPagination(Map conditions);
}