package mycourse.onkshare.mapper;

import mycourse.onkshare.model.FileDesc;
import mycourse.onkshare.model.FileDescExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import java.util.List;

@MapperScan
public interface FileDescMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    long countByExample(FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int deleteByExample(FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int deleteByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int insert(FileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int insertSelective(FileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    List<FileDesc> selectByExampleWithBLOBs(FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    List<FileDesc> selectByExample(FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    FileDesc selectByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileDesc record, @Param("example") FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") FileDesc record, @Param("example") FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByExample(@Param("record") FileDesc record, @Param("example") FileDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByPrimaryKeySelective(FileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(FileDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_desc
     *
     * @mbg.generated Mon Feb 13 15:03:37 CST 2017
     */
    int updateByPrimaryKey(FileDesc record);
}