package mycourse.onkshare.mapper;

import java.util.List;
import mycourse.onkshare.model.FileDeleted;
import mycourse.onkshare.model.FileDeletedExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface FileDeletedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    long countByExample(FileDeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int deleteByExample(FileDeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int insert(FileDeleted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int insertSelective(FileDeleted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    List<FileDeleted> selectByExample(FileDeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    FileDeleted selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileDeleted record, @Param("example") FileDeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int updateByExample(@Param("record") FileDeleted record, @Param("example") FileDeletedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int updateByPrimaryKeySelective(FileDeleted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_deleted
     *
     * @mbg.generated Wed Apr 05 17:24:39 CST 2017
     */
    int updateByPrimaryKey(FileDeleted record);
}