package mycourse.onkshare.mapper;

import java.util.List;
import java.util.Map;

import mycourse.onkshare.model.Notification;
import mycourse.onkshare.model.NotificationExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    long countByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int deleteByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    Long insert(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int insertSelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    List<Notification> selectByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    Notification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") Notification record, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int updateByExample(@Param("record") Notification record, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int updateByPrimaryKeySelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notification
     *
     * @mbg.generated Sat Apr 01 19:45:43 CST 2017
     */
    int updateByPrimaryKey(Notification record);

    List<Notification> selectNotificationForPagination(Map conditions);
}