package mycourse.onkshare.mapper;

import java.util.List;
import java.util.Map;

import mycourse.onkshare.model.SitesMessage;
import mycourse.onkshare.model.SitesMessageExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface SitesMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    long countByExample(SitesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int deleteByExample(SitesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int insert(SitesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int insertSelective(SitesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    List<SitesMessage> selectByExample(SitesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    SitesMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") SitesMessage record, @Param("example") SitesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int updateByExample(@Param("record") SitesMessage record, @Param("example") SitesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int updateByPrimaryKeySelective(SitesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sites_message
     *
     * @mbg.generated Tue Mar 28 09:30:22 CST 2017
     */
    int updateByPrimaryKey(SitesMessage record);

    List<SitesMessage> selectMessage(Map conditions);

    Long selectMessageFloorMax();
}